/**
 * Generates src/lib/phMap.ts: a simplified SVG outline of the Philippines and
 * the projection constants used to place route stops on it.
 *
 * Source: Natural Earth 1:10m Admin 0 countries (public domain).
 * Run: node scripts/build-ph-map.mjs   (only needed to regenerate the map)
 */
import { writeFileSync } from 'node:fs';

const SOURCE_URL =
  'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_admin_0_countries.geojson';
const OUTPUT = new URL('../src/lib/phMap.ts', import.meta.url);

// Bounds cover the main archipelago; the far-west Kalayaan islets are clipped.
const BOUNDS = { minLng: 116.8, maxLng: 126.8, minLat: 4.4, maxLat: 21.3 };
const PX_PER_DEGREE = 60;
const LNG_SCALE = Math.cos((12.8 * Math.PI) / 180); // equirectangular at mid-latitude
const TOLERANCE_PX = 0.7;
const MIN_ISLAND_AREA_PX = 3;

const project = ([lng, lat]) => [
  (lng - BOUNDS.minLng) * PX_PER_DEGREE * LNG_SCALE,
  (BOUNDS.maxLat - lat) * PX_PER_DEGREE,
];

function perpendicularDistance([x, y], [x1, y1], [x2, y2]) {
  const dx = x2 - x1;
  const dy = y2 - y1;
  const length = Math.hypot(dx, dy);
  if (length === 0) return Math.hypot(x - x1, y - y1);
  return Math.abs(dy * x - dx * y + x2 * y1 - y2 * x1) / length;
}

/** Douglas–Peucker simplification. */
function simplify(points, tolerance) {
  if (points.length < 3) return points;
  let maxDistance = 0;
  let index = 0;
  for (let i = 1; i < points.length - 1; i++) {
    const distance = perpendicularDistance(points[i], points[0], points.at(-1));
    if (distance > maxDistance) {
      maxDistance = distance;
      index = i;
    }
  }
  if (maxDistance <= tolerance) return [points[0], points.at(-1)];
  return [...simplify(points.slice(0, index + 1), tolerance).slice(0, -1), ...simplify(points.slice(index), tolerance)];
}

function area(points) {
  let sum = 0;
  for (let i = 0; i < points.length; i++) {
    const [x1, y1] = points[i];
    const [x2, y2] = points[(i + 1) % points.length];
    sum += x1 * y2 - x2 * y1;
  }
  return Math.abs(sum / 2);
}

const response = await fetch(SOURCE_URL);
if (!response.ok) throw new Error(`Download failed: HTTP ${response.status}`);
const geojson = await response.json();
const philippines = geojson.features.find((f) => f.properties.ADM0_A3 === 'PHL');
if (!philippines) throw new Error('Philippines not found in source data');

const width = Math.round((BOUNDS.maxLng - BOUNDS.minLng) * PX_PER_DEGREE * LNG_SCALE);
const height = Math.round((BOUNDS.maxLat - BOUNDS.minLat) * PX_PER_DEGREE);

const rings = philippines.geometry.coordinates
  .map((polygon) => polygon[0]) // outer rings only; lakes don't matter at this scale
  .filter((ring) => ring.every(([lng]) => lng >= BOUNDS.minLng))
  .map((ring) => simplify(ring.map(project), TOLERANCE_PX))
  .filter((ring) => ring.length >= 3 && area(ring) >= MIN_ISLAND_AREA_PX);

const path = rings
  .map((ring) => `M${ring.map(([x, y]) => `${x.toFixed(1)} ${y.toFixed(1)}`).join('L')}Z`)
  .join('');

const pointCount = rings.reduce((n, ring) => n + ring.length, 0);

writeFileSync(
  OUTPUT,
  `// Generated by scripts/build-ph-map.mjs from Natural Earth (public domain). Do not edit.

export const PH_MAP = {
  width: ${width},
  height: ${height},
  /** ${rings.length} islands, ${pointCount} points. */
  path: '${path}',
} as const;

const BOUNDS = ${JSON.stringify(BOUNDS)};
const PX_PER_DEGREE = ${PX_PER_DEGREE};
const LNG_SCALE = ${LNG_SCALE};

/** Projects a coordinate onto the map's SVG coordinate space. */
export function projectToMap(lat: number, lng: number): { x: number; y: number } {
  return {
    x: (lng - BOUNDS.minLng) * PX_PER_DEGREE * LNG_SCALE,
    y: (BOUNDS.maxLat - lat) * PX_PER_DEGREE,
  };
}
`,
);

console.log(`Wrote ${OUTPUT.pathname}: ${rings.length} islands, ${pointCount} points, ${path.length} chars`);
